# Generated by Django 4.1.3 on 2022-12-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=40)),
                ('codigo_articulo', models.IntegerField()),
                ('numero_dia', models.IntegerField()),
            ],
        ),
    ]
