from django.urls import path
from AppBlog import views

urlpatterns = [
    path('', views.inicio,name='inicio' ),
    path('post/', views.post,name='articulos'),
    path('postApi/', views.postapi),
    path('usuario/', views.usuario),
    path('busquedaPost/', views.buscarPost,name='buscador'),
    path('buscar/', views.buscar),
    path('leerPost/', views.leer_post),
    path('crearPost/', views.crear_post),
    path('editarPost/', views.editar_post),
    path('eliminarPost/', views.eliminar_post),
    path('post/list/', views.Postlist.as_view(), name='New'),
    path('post/create/', views.PostCreate.as_view(), name='List'),
    path('post/edite/<pk>', views.PostEdite.as_view(), name='Edit'),
    path('post/delete/<pk>', views.PostDelete.as_view(), name='Delete'),
    path('post/detail/<pk>', views.PostDetail.as_view(), name='Detail'),
    path('usuarios/', views.usuario,name='usuario' ),
    path('categorias/', views.categorias,name='categorias' ),
    path('autores/', views.usuariosapi),
    path('categorias_post/', views.categoriasapi),
    path('busquedaCategorias/', views.buscarcategoria,name='buscadorcategoria'),
    path('busquedaAutores/', views.buscarautor,name='buscadorautor'),
    path('leerCategorias/', views.leer_categorias),
    path('crearCategorias/', views.crear_categorias),
    path('editarCategorias/', views.editar_categorias),
    path('eliminarCategorias/', views.eliminar_categorias),
    path('leerAutores/', views.leer_autores),
    path('crearAutores/', views.crear_autores),
    path('editarAutores/', views.editar_autores),
    path('eliminarAutores/', views.eliminar_autores),
    path('categorias/list/', views.Categorialist.as_view(), name='List Cat'),
    path('categorias/create/', views.CategoriaCreate.as_view(), name='New Cat'),
    path('categorias/edite/<pk>', views.CategoriaEdite.as_view(), name='Edit Cat'),
    path('categorias/delete/<pk>', views.CategoriaDelete.as_view(), name='Delete Cat'),
    path('categorias/detail/<pk>', views.CategoriaDetail.as_view(), name='Detail Cat'),
    path('autores/list/', views.Usuariolist.as_view(), name='List Au'),
    path('autores/create/', views.UsuarioCreate.as_view(), name='New Au'),
    path('autores/edite/<pk>', views.UsuarioEdite.as_view(), name='Edit Au'),
    path('autores/delete/<pk>', views.UsuarioDelete.as_view(), name='Delete Au'),
    path('autores/detail/<pk>', views.UsuarioDetail.as_view(), name='Detail Au'),
]